#!/usr/bin/env python3

# Standard libraries
import os
import subprocess

# Feature libraries
import toml
import click


@click.group(name="jobrunner")
def jobrunner():
    """
    CLI for managing simulations jobs
    """
    pass


@jobrunner.command(name="submit")
@click.argument("workdir", default=None, type=str)
def submit(workdir):
    """
    Command to submit a job from a working directory
    """
    # Read TOML file and replace
    job = toml.load("job.info")
    job["name"] = workdir.split("/")[-1] + ".sh"

    # Get current directory
    os.chdir(workdir)
    workdir = os.getcwd()

    # Build inputfile
    print(f'Creating input file: {workdir + "/" + job["inputfile"]}')

    return_code = _create_inputfile(job, workdir)
    if return_code != 0:
        raise ValueError()

    # Build jobfile
    print(f'Creating job file: {workdir + "/" + "job.sh"}')

    return_code = _create_jobfile(job, workdir)
    if return_code != 0:
        raise ValueError()

    # Submit job
    print("Submitting job")

    subprocess.run(f'{job["schedular"]} {job["name"]}', shell=True, check=True)


@jobrunner.command(name="clean")
@click.argument("workdir", default=None, type=str)
def clean(workdir):
    """
    Command to clean artifacts from working directory
    """
    job = toml.load("job.info")
    job["name"] = workdir.split("/")[-1] + ".sh"

    # run cleanup
    process = subprocess.run(
        f'rm -vf {workdir + "/" + job["inputfile"]} {workdir + "/" + job["name"]}',
        shell=True,
        check=True,
    )


def _create_inputfile(job, workdir):
    """
    create an input file for a given simulation recursively using
    `job.input` between `basedir` and `workdir`

    `job`     :  Job dictionary
    `workdir` :  Current job directory
    """
    # get inputfile_list from internal method
    inputfile_list = _get_file_list(job["basedir"], workdir, "job.input")

    # run a subprocess to build flash.par
    process = subprocess.run(
        f'rm -f {job["inputfile"]} && cat {" ".join(inputfile_list)} > {job["inputfile"]}',
        shell=True,
        check=True,
    )

    return process.returncode


def _create_jobfile(job, workdir):
    """
    create `jobrunner.sh` for a given simulation recursively using
    `inputfile` between `basedir` and `workdir`

    `job`     :  Job dictionary
    `workdir` :  Current job directory
    """
    # get config_list and submit_list from internal method
    config_list = _get_file_list(job["basedir"], workdir, "job.config")
    submit_list = _get_file_list(job["basedir"], workdir, "job.submit")

    # set header for the submit script
    with open(workdir + "/" + job["name"], "w") as jobfile:
        jobfile.write("#!/bin/bash\n\n")

    # run the subprocess
    process = subprocess.run(
        f'cat {" ".join(submit_list)} {" ".join(config_list)} >> {job["name"]}',
        shell=True,
        check=True,
    )

    return process.returncode


def _get_file_list(basedir, workdir, filename):
    """
    Get a list of paths containing a file with name
    `filename` between `basedir` and `workdir`

    Arguments
    ---------
    `basedir`  :  Base directory (top level) of a project
    `workdir`  :  Current job directory
    `filename` :  Name of the file to query

    Returns
    --------
    file_list :   A list of path containing the file
    """

    # Get a list of directory levels between `basedir` and `workdir`
    dir_levels = [
        level for level in workdir.split("/") if level not in basedir.split("/")
    ]

    # Create an empty file list
    file_list = []

    # start with current level
    current_level = basedir

    # Loop over directory levels
    for level in [""] + dir_levels:

        # Set current level
        current_level = current_level + "/" + level

        # set file path
        file_path = current_level + "/" + filename

        # Append to file list if path exists
        if os.path.exists(file_path):
            file_list.append(file_path)

    return file_list


if __name__ == "__main__":
    jobrunner()
